apiVersion: v1
kind: Secret
metadata:
  namespace: spring
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MYSQL_DATABASE: ZHJ1cGFsLWRhdGFiYXNl
  MYSQL_USER: cm9vdA==
  
#kubectl create secret generic mysql-secret --from-literal=MYSQL_ROOT_PASSWORD=dlatl#00 --from-literal=MYSQL_DATABASE=spring --from-literal=MYSQL_USER=root -n spring

