apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: spring
  name: mysql-pv
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /home/master01/k8s/mysql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: spring
  name: mysql-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
