apiVersion: v1
kind: Service
metadata:
  namespace: spring
  name: mysql-service
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 31000
  selector:
    app: mysql              
  type: NodePort    